[project]
name = "proj1"
version = "0.1.0"
description = "Computer Vision Project 1 - Filtering and Hybrid Images"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
    "pillow>=12.0.0",
    "scipy>=1.16.3",
]
